name: easy_downloader
description: Easy Downloader is a simpled easy to use plugin to download files from the internet.
version: 0.0.21-dev-04
homepage: https://github.com/linkkader/easy_downloader/blob/main/example/main.dart
repository: https://github.com/linkkader/easy_downloader

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.3.0
  mason_logger: ^0.2.4
  pub_updater: ^0.3.0
  http: ^0.13.5
  #locale storage
  isar: ^3.1.0+1
  #logging
  logger: ^1.0.0
  chunked_stream: ^1.4.1



dev_dependencies:
  build_verify: ^3.0.0
  mocktail: ^0.3.0

  build_runner: ^2.1.8
  build_version: ^2.0.0
  isar_generator: ^3.1.0+1
  lints: ^2.1.0
  test: ^1.19.2
  flutter_lints: ^2.0.0
  analyzer: ^5.13.0

executables:
  easy_downloader: