name: easy_downloader
description: Easy Downloader is a simpled easy to use plugin to download files from the internet.
version: 0.0.18-dev-07
homepage: https://github.com/linkkader/easy_downloader/blob/main/example/lib/main.dart
repository: https://github.com/linkkader/easy_downloader

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  http: ^0.13.5
  #locale storage
  isar: ^3.1.0+1
  #logging
  logger: ^1.0.0
  chunked_stream: ^1.4.1


dev_dependencies:
  build_runner: ^2.1.8
  build_version: ^2.0.0
  isar_generator: ^3.1.0+1
  lints: ^2.1.0
  test: ^1.19.2
  flutter_lints: ^2.0.0
  analyzer: ^5.13.0
