name: easy_downloader
description: A new Flutter project.
version: 0.0.1
homepage:

environment:
  sdk: '>=2.18.0 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter_local_notifications: ^12.0.1+1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.0.11
  flutter:
    sdk: flutter

dev_dependencies:
  hive_generator: ^1.1.3
  build_runner: ^2.1.8
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  generate: true