name: easy_downloader
description: Easy Downloader is a simple and easy to use plugin to download files from the internet.
version: 0.0.13
homepage: https://github.com/linkkader/easy_downloader/blob/main/example/lib/main.dart
repository: https://github.com/linkkader/easy_downloader

environment:
  sdk: ">=2.19.0 <3.0.0"

dependencies:
  http: ^0.13.5
  args: ^2.3.1
  chunked_stream: ^1.4.1
  cli_completion: ^0.2.0
  #locale storage
  isar: ^3.0.5
  #logging
  logger: any
  mason_logger: ^0.2.4
  pub_updater: ^0.2.4

dev_dependencies:
  build_runner: ^2.1.8
  build_verify: ^3.0.0
  build_version: ^2.0.0
  isar_generator: ^3.0.2
  lints: ^2.0.0
  mocktail: ^0.3.0
  test: ^1.19.2
  very_good_analysis: ^4.0.0

executables:
  easy_downloader:
